name: MineplayerServer
version: '${version}'
main: MineplayerServer
api-version: 1.19
depend: [ ProtocolLib, Multiverse-Core, Kotlin ]
authors: [ JeffLegendPower ]
description: Training environment for Mineplayer
