name: MineplayerServer
version: '${version}'
main: io.github.jefflegendpower.mineplayerserver.MineplayerServer
api-version: 1.19
depend: [ ProtocolLib, Multiverse-Core, MCKotlin-Paper ]
authors: [ JeffLegendPower ]
description: Training environment for Mineplayer
