name: Build Mineplayer Server Plugin on Push
on:
  push:
    paths:
      - 'mineplayer/MineplayerServer/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        working-directory: ./mineplayer/MineplayerServer
        run: gradle build
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: mineplayer/MineplayerServer/build/libs/