name: Build Mineplayer Server Plugin on Push
on:
  push:
    paths:
      - 'MineplayerServer/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gralde-build-action@v2
      - name: Build with Gradle
        working-directory: ./MineplayerServer
        run: ./gradlew build